Repository Netcracker/qubership-integration-engine, pull requests merged in 2025-04, with the labels that each got.

#112 #111 Removed use of keys retryCount and retryDelay in exchange properties
  src/main/java/org/qubership/integration/platform/engine/model/logging/ElementRetryProperties.java
  src/main/java/org/qubership/integration/platform/engine/service/debugger/CamelDebugger.java
  src/main/java/org/qubership/integration/platform/engine/service/debugger/logging/ChainLogger.java
Labels: bug

#121 #117 Removed deprecated variables injection in routes
  src/main/java/org/qubership/integration/platform/engine/service/VariablesService.java
Labels: enhancement

#126 Added bluegreenState property into exchange property
  src/main/java/org/qubership/integration/platform/engine/configuration/ExchangePropertyAutoConfiguration.java
  src/main/java/org/qubership/integration/platform/engine/model/constants/CamelConstants.java
  src/main/java/org/qubership/integration/platform/engine/service/ExchangePropertyService.java
  src/main/java/org/qubership/integration/platform/engine/service/debugger/CamelDebugger.java
Labels: feature
