Repository Netcracker/qubership-integration-engine, pull requests merged in 2025-09, with the labels that each got.

#242 fix: [v0.1] #241 Added optimizations for insert and delete operations for checkpoints
  src/main/java/org/qubership/integration/platform/engine/persistence/shared/entity/Checkpoint.java
  src/main/resources/application-development.yml
  src/main/resources/application.yml
Labels: bug, enhancement

#243 fix: #241 Added optimizations for insert and delete operations for checkpoints
  src/main/java/org/qubership/integration/platform/engine/persistence/shared/entity/Checkpoint.java
  src/main/resources/application-development.yml
  src/main/resources/application.yml
Labels: bug, enhancement

#247 feat: groupId updated to org.qubership.integration.platform
  pom.xml
Labels: enhancement, feature

#248 feat: [v0.1] groupId updated to org.qubership.integration.platform
  pom.xml
Labels: feature

#240 Fix for oid performance issue
  src/main/java/org/qubership/integration/platform/engine/camel/processors/checkpoint/ContextLoaderProcessor.java
  src/main/java/org/qubership/integration/platform/engine/persistence/shared/entity/Checkpoint.java
  src/main/java/org/qubership/integration/platform/engine/persistence/shared/entity/Property.java
  src/main/resources/db/migration/postgresql/static/V104_000__deprecate_oid_fields.sql
Labels: bug, enhancement

#249 feat(ci): Broadcast maven-release-v2 workflow to QIP repos
  .github/workflows/maven-release-v2.yaml
Labels: enhancement
